'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Plus, Check, X, Pencil, CreditCard, Eye, Paperclip, WalletCards } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { Select } from '@/components/ui/Select';
import { Textarea } from '@/components/ui/Textarea';
import { Badge } from '@/components/ui/Badge';
import { Modal } from '@/components/ui/Modal';

interface Payment { id:string; amount:number|string; currency:string; payment_method:string; payment_date:string; reference_number:string; transaction_id:string|null; proof_url:string|null; status:'Pending'|'Verified'|'Rejected'; rejection_reason:string|null; notes:string|null; created_at:string }
interface CurrencySummary { currency:string; recorded:number; verified:number; pending:number; rejected:number }
interface PaymentsTabProps { projectId:string; isCompleted?:boolean }
const MAX_PROOF_SIZE=10*1024*1024;
const PAYMENT_METHOD_OPTIONS=[{value:'',label:'Select payment method'},{value:'Bank Transfer',label:'Bank Transfer'},{value:'Mobile Money',label:'Mobile Money'},{value:'PayPal',label:'PayPal'},{value:'Western Union',label:'Western Union'},{value:'Cash',label:'Cash'},{value:'Other',label:'Other'}];
const CURRENCY_OPTIONS=[{value:'USD',label:'USD'},{value:'LRD',label:'LRD'}];
const newForm=()=>({amount:'',currency:'USD',payment_method:'',payment_date:new Date().toISOString().split('T')[0],reference_number:'',transaction_id:'',proof_url:'',notes:''});
const formatMoney=(amount:number,currency:string)=>new Intl.NumberFormat('en-US',{style:'currency',currency,minimumFractionDigits:2}).format(amount);
const formatDate=(value:string)=>new Date(`${value}T00:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
const statusVariant=(status:Payment['status'])=>status==='Verified'?'success':status==='Rejected'?'danger':'warning';
function fileToBase64(file:File):Promise<string>{return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const result=String(reader.result||'');resolve(result.includes(',')?result.split(',')[1]:result)};reader.onerror=()=>reject(new Error('Unable to read payment proof file'));reader.readAsDataURL(file)})}

export function PaymentsTab({projectId,isCompleted=false}:PaymentsTabProps){
 const [payments,setPayments]=useState<Payment[]>([]); const [isLoading,setIsLoading]=useState(true); const [isSubmitting,setIsSubmitting]=useState(false); const [error,setError]=useState<string|null>(null);
 const [showPaymentModal,setShowPaymentModal]=useState(false); const [editingPayment,setEditingPayment]=useState<Payment|null>(null); const [form,setForm]=useState(newForm()); const [proofFile,setProofFile]=useState<File|null>(null);
 const [showRejectModal,setShowRejectModal]=useState(false); const [rejectingPayment,setRejectingPayment]=useState<Payment|null>(null); const [rejectionReason,setRejectionReason]=useState('');
 const loadPayments=useCallback(async()=>{try{setIsLoading(true);setError(null);const response=await fetch(`/api/projects/${projectId}/payments`,{cache:'no-store'});const result=await response.json();if(!response.ok)throw new Error(result?.error||'Failed to load payments');setPayments(result.payments||[])}catch(err){setError(err instanceof Error?err.message:'Failed to load payments')}finally{setIsLoading(false)}},[projectId]);
 useEffect(()=>{void loadPayments()},[loadPayments]);
 const summaries=useMemo(()=>{const grouped=new Map<string,CurrencySummary>();for(const payment of payments){const currency=String(payment.currency||'USD').toUpperCase();const current=grouped.get(currency)||{currency,recorded:0,verified:0,pending:0,rejected:0};const amount=Number(payment.amount||0);current.recorded+=amount;if(payment.status==='Verified')current.verified+=amount;if(payment.status==='Pending')current.pending+=amount;if(payment.status==='Rejected')current.rejected+=amount;grouped.set(currency,current)}return Array.from(grouped.values()).sort((a,b)=>a.currency==='USD'?-1:b.currency==='USD'?1:a.currency.localeCompare(b.currency))},[payments]);
 const openNewPayment=()=>{setEditingPayment(null);setForm(newForm());setProofFile(null);setError(null);setShowPaymentModal(true)};
 const openEditPayment=(payment:Payment)=>{setEditingPayment(payment);setProofFile(null);setForm({amount:String(payment.amount),currency:payment.currency,payment_method:payment.payment_method,payment_date:payment.payment_date,reference_number:payment.reference_number||'',transaction_id:payment.transaction_id||'',proof_url:payment.proof_url||'',notes:payment.notes||''});setError(null);setShowPaymentModal(true)};
 const closePaymentModal=()=>{if(isSubmitting)return;setShowPaymentModal(false);setEditingPayment(null);setForm(newForm());setProofFile(null)};
 const uploadProof=async(file:File)=>{if(file.size>MAX_PROOF_SIZE)throw new Error('Payment proof cannot exceed 10 MB');const fileData=await fileToBase64(file);const response=await fetch(`/api/projects/${projectId}/payments/proof`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fileName:file.name,fileType:file.type,fileSize:file.size,fileData})});const result=await response.json();if(!response.ok)throw new Error(result?.error||'Failed to upload payment proof');return String(result.path)};
 const removeProofPath=async(path:string)=>{await fetch(`/api/projects/${projectId}/payments/proof`,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({path})})};
 const savePayment=async()=>{if(!form.amount||!form.payment_method||!form.payment_date)return;let stagedProofPath:string|null=null;const oldProofPath=editingPayment?.proof_url||null;try{setIsSubmitting(true);setError(null);if(proofFile)stagedProofPath=await uploadProof(proofFile);const proofUrl=stagedProofPath||form.proof_url||null;const response=await fetch(`/api/projects/${projectId}/payments`,{method:editingPayment?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editingPayment?{action:'update',paymentId:editingPayment.id,amount:Number(form.amount),currency:form.currency,payment_method:form.payment_method,payment_date:form.payment_date,transaction_id:form.transaction_id,proof_url:proofUrl,notes:form.notes}:{amount:Number(form.amount),currency:form.currency,payment_method:form.payment_method,payment_date:form.payment_date,reference_number:form.reference_number,transaction_id:form.transaction_id,proof_url:proofUrl,notes:form.notes})});const result=await response.json();if(!response.ok){if(stagedProofPath)await removeProofPath(stagedProofPath);throw new Error(result?.error||'Failed to save payment')}if(stagedProofPath&&oldProofPath&&oldProofPath!==stagedProofPath)await removeProofPath(oldProofPath);closePaymentModal();await loadPayments()}catch(err){setError(err instanceof Error?err.message:'Failed to save payment')}finally{setIsSubmitting(false)}};
 const viewProof=async(paymentId:string)=>{try{setError(null);const response=await fetch(`/api/projects/${projectId}/payments/proof?paymentId=${encodeURIComponent(paymentId)}`,{cache:'no-store'});const result=await response.json();if(!response.ok)throw new Error(result?.error||'Failed to open payment proof');window.open(result.url,'_blank','noopener,noreferrer')}catch(err){setError(err instanceof Error?err.message:'Failed to open payment proof')}};
 const verifyPayment=async(paymentId:string)=>{try{setIsSubmitting(true);setError(null);const response=await fetch(`/api/projects/${projectId}/payments`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'verify',paymentId})});const result=await response.json();if(!response.ok)throw new Error(result?.error||'Failed to verify payment');await loadPayments()}catch(err){setError(err instanceof Error?err.message:'Failed to verify payment')}finally{setIsSubmitting(false)}};
 const openRejectPayment=(payment:Payment)=>{setRejectingPayment(payment);setRejectionReason('');setError(null);setShowRejectModal(true)};
 const rejectPayment=async()=>{if(!rejectingPayment||!rejectionReason.trim())return;try{setIsSubmitting(true);setError(null);const response=await fetch(`/api/projects/${projectId}/payments`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'reject',paymentId:rejectingPayment.id,rejection_reason:rejectionReason.trim()})});const result=await response.json();if(!response.ok)throw new Error(result?.error||'Failed to reject payment');setShowRejectModal(false);setRejectingPayment(null);setRejectionReason('');await loadPayments()}catch(err){setError(err instanceof Error?err.message:'Failed to reject payment')}finally{setIsSubmitting(false)}};
 return <>
  <section className="overflow-hidden rounded-2xl border border-[var(--border-subtle)] bg-white shadow-sm">
   <header className="flex flex-col gap-4 border-b border-[var(--border-subtle)] bg-[var(--surface-subtle)]/70 p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div className="flex items-start gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-green/10"><WalletCards className="h-5 w-5 text-brand-green"/></div><div><h3 className="font-semibold text-[var(--text-primary)]">Project payments</h3><p className="mt-1 text-sm text-[var(--text-secondary)]">Record, verify and track project payments and supporting proof.</p></div></div>{!isCompleted&&<Button onClick={openNewPayment}><Plus className="mr-2 h-4 w-4"/>Record Payment</Button>}</header>
   <div className="space-y-6 p-5 sm:p-6">{error&&<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
    {summaries.length===0?<div className="grid gap-3 sm:grid-cols-3">{['Total Recorded','Verified Payments','Pending Verification'].map(label=><div key={label} className="rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-subtle)] p-4"><p className="text-xs font-semibold uppercase tracking-[0.08em] text-[var(--text-muted)]">{label}</p><p className="mt-2 text-xl font-semibold text-[var(--text-primary)]">{formatMoney(0,'USD')}</p></div>)}</div>:summaries.map(s=><div key={s.currency} className="rounded-2xl border border-[var(--border-subtle)] p-4"><div className="mb-4 flex items-center justify-between"><p className="font-semibold">{s.currency} summary</p><Badge variant="secondary">{s.currency}</Badge></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Recorded',s.recorded,''],['Verified',s.verified,'text-green-700'],['Pending',s.pending,'text-amber-700'],['Rejected',s.rejected,'text-red-700']].map(([label,value,tone])=><div key={String(label)} className="rounded-xl bg-[var(--surface-subtle)] p-4"><p className="text-xs font-medium text-[var(--text-muted)]">{label}</p><p className={`mt-1 text-xl font-semibold ${tone}`}>{formatMoney(Number(value),s.currency)}</p></div>)}</div></div>)}
    {isLoading?<div className="py-14 text-center text-sm text-[var(--text-secondary)]">Loading payments...</div>:payments.length===0?<div className="rounded-2xl border border-dashed border-[var(--border-default)] bg-[var(--surface-subtle)] py-14 text-center"><CreditCard className="mx-auto h-9 w-9 text-gray-300"/><p className="mt-3 font-semibold">No payments recorded</p><p className="mt-1 text-sm text-[var(--text-secondary)]">Payment activity will appear here.</p></div>:<div className="overflow-x-auto rounded-xl border border-[var(--border-subtle)]"><table className="w-full min-w-[900px]"><thead className="bg-[var(--surface-subtle)]"><tr>{['Date','Reference','Method','Amount','Status','Proof','Actions'].map(h=><th key={h} className={`px-4 py-3 text-xs font-semibold uppercase tracking-[0.06em] text-[var(--text-muted)] ${h==='Actions'?'text-right':'text-left'}`}>{h}</th>)}</tr></thead><tbody className="divide-y divide-[var(--border-subtle)]">{payments.map(payment=><tr key={payment.id} className="transition hover:bg-[var(--surface-subtle)]/60"><td className="px-4 py-4 text-sm">{formatDate(payment.payment_date)}</td><td className="px-4 py-4"><p className="font-mono text-sm font-medium text-brand-green">{payment.reference_number}</p>{payment.transaction_id&&<p className="mt-1 text-xs text-[var(--text-muted)]">Transaction: {payment.transaction_id}</p>}</td><td className="px-4 py-4 text-sm">{payment.payment_method}</td><td className="px-4 py-4 font-semibold">{formatMoney(Number(payment.amount),payment.currency)}</td><td className="px-4 py-4"><Badge variant={statusVariant(payment.status) as any}>{payment.status}</Badge>{payment.rejection_reason&&<p className="mt-1 max-w-[220px] text-xs text-red-600">{payment.rejection_reason}</p>}</td><td className="px-4 py-4">{payment.proof_url?<Button size="sm" variant="ghost" onClick={()=>viewProof(payment.id)}><Eye className="mr-1 h-4 w-4"/>View</Button>:<span className="text-sm text-[var(--text-muted)]">None</span>}</td><td className="px-4 py-4"><div className="flex justify-end gap-2">{payment.status==='Pending'&&!isCompleted&&<><Button size="sm" variant="ghost" onClick={()=>openEditPayment(payment)} disabled={isSubmitting}><Pencil className="h-4 w-4"/></Button><Button size="sm" variant="secondary" onClick={()=>verifyPayment(payment.id)} disabled={isSubmitting}><Check className="h-4 w-4"/></Button><Button size="sm" variant="ghost" onClick={()=>openRejectPayment(payment)} disabled={isSubmitting}><X className="h-4 w-4"/></Button></>}</div></td></tr>)}</tbody></table></div>}
   </div>
  </section>
  <Modal isOpen={showPaymentModal} onClose={closePaymentModal} title={editingPayment?'Edit Pending Payment':'Record Payment'}><div className="space-y-4">{error&&<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<div className="grid gap-4 sm:grid-cols-2"><Input label="Amount" type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm(p=>({...p,amount:e.target.value}))} placeholder="0.00"/><Select label="Currency" value={form.currency} onChange={e=>setForm(p=>({...p,currency:e.target.value}))} options={CURRENCY_OPTIONS}/></div><Select label="Payment Method" value={form.payment_method} onChange={e=>setForm(p=>({...p,payment_method:e.target.value}))} options={PAYMENT_METHOD_OPTIONS}/><Input label="Payment Date" type="date" value={form.payment_date} onChange={e=>setForm(p=>({...p,payment_date:e.target.value}))}/>{!editingPayment&&<Input label="Reference Number" value={form.reference_number} onChange={e=>setForm(p=>({...p,reference_number:e.target.value}))} placeholder="Leave blank to generate automatically"/>}<Input label="Transaction ID" value={form.transaction_id} onChange={e=>setForm(p=>({...p,transaction_id:e.target.value}))} placeholder="Optional"/><div><label className="mb-1.5 block text-sm font-medium">{editingPayment?.proof_url?'Replace Payment Proof':'Payment Proof'}</label><label className="flex cursor-pointer items-center gap-3 rounded-xl border border-[var(--border-default)] bg-[var(--surface-subtle)] px-4 py-3"><Paperclip className="h-4 w-4 text-brand-green"/><span className="text-sm">{proofFile?proofFile.name:editingPayment?.proof_url?'Choose a replacement file':'Choose receipt or payment proof'}</span><input type="file" className="hidden" accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx" onChange={e=>{const file=e.target.files?.[0]||null;if(file&&file.size>MAX_PROOF_SIZE){setError('Payment proof cannot exceed 10 MB');setProofFile(null);return}setError(null);setProofFile(file)}}/></label><p className="mt-1 text-xs text-[var(--text-muted)]">PDF, JPG, PNG, WEBP, DOC or DOCX. Maximum 10 MB.</p></div><Textarea label="Notes" value={form.notes} onChange={e=>setForm(p=>({...p,notes:e.target.value}))} rows={3} placeholder="Optional payment note"/></div><div className="mt-6 flex justify-end gap-3"><Button variant="secondary" onClick={closePaymentModal} disabled={isSubmitting}>Cancel</Button><Button onClick={savePayment} disabled={isSubmitting||!form.amount||!form.payment_method||!form.payment_date}>{isSubmitting?'Saving...':editingPayment?'Save Changes':'Record Payment'}</Button></div></Modal>
  <Modal isOpen={showRejectModal} onClose={()=>{if(!isSubmitting){setShowRejectModal(false);setRejectingPayment(null);setRejectionReason('')}}} title="Reject Payment"><div className="space-y-4">{error&&<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<p className="text-sm text-[var(--text-secondary)]">Provide the reason this payment cannot be verified.</p><Textarea label="Rejection Reason" value={rejectionReason} onChange={e=>setRejectionReason(e.target.value)} rows={4} placeholder="Enter the rejection reason"/></div><div className="mt-6 flex justify-end gap-3"><Button variant="secondary" onClick={()=>{setShowRejectModal(false);setRejectingPayment(null);setRejectionReason('')}} disabled={isSubmitting}>Cancel</Button><Button onClick={rejectPayment} disabled={isSubmitting||!rejectionReason.trim()}>{isSubmitting?'Rejecting...':'Reject Payment'}</Button></div></Modal>
 </>;
}
export default PaymentsTab;
