'use client';

import { AlertCircle, LoaderCircle, MessageSquareText, RefreshCw, Send } from 'lucide-react';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { Button, Card } from '@/components/ui';

type ProjectMessage = { id: string; senderType: 'staff' | 'client'; senderName: string; message: string; createdAt: string; isCurrentUser: boolean; };
type MessagesResponse = { messages?: ProjectMessage[]; error?: string; };
function formatMessageDate(value: string) { const date = new Date(value); if (Number.isNaN(date.getTime())) return 'Date unavailable'; return new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }).format(date); }

export default function StaffProjectMessages({ projectId }: { projectId: string }) {
  const [messages, setMessages] = useState<ProjectMessage[]>([]); const [draft, setDraft] = useState('');
  const [isLoading, setIsLoading] = useState(true); const [isSending, setIsSending] = useState(false); const [error, setError] = useState<string | null>(null);
  const loadMessages = useCallback(async () => { try { setIsLoading(true); setError(null); const response = await fetch(`/api/projects/${encodeURIComponent(projectId)}/messages`, { credentials: 'include', cache: 'no-store', headers: { Accept: 'application/json' } }); const data = (await response.json()) as MessagesResponse; if (!response.ok) throw new Error(data.error || 'Unable to retrieve project messages.'); setMessages(data.messages ?? []); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Unable to retrieve project messages.'); } finally { setIsLoading(false); } }, [projectId]);
  useEffect(() => { void loadMessages(); }, [loadMessages]);
  const sendMessage = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const message = draft.trim(); if (!message || isSending) return; try { setIsSending(true); setError(null); const response = await fetch(`/api/projects/${encodeURIComponent(projectId)}/messages`, { method: 'POST', credentials: 'include', headers: { Accept: 'application/json', 'Content-Type': 'application/json' }, body: JSON.stringify({ message }) }); const data = (await response.json()) as MessagesResponse; if (!response.ok) throw new Error(data.error || 'Unable to send the message.'); setDraft(''); setMessages(data.messages ?? []); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Unable to send the message.'); } finally { setIsSending(false); } };

  return <Card variant="bordered" padding="none" className="overflow-hidden rounded-2xl border-[var(--border-subtle)] shadow-sm">
    <div className="flex flex-col gap-4 border-b border-[var(--border-subtle)] bg-[var(--surface-subtle)]/70 px-5 py-5 sm:flex-row sm:items-center sm:justify-between sm:px-6">
      <div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-brand-green/10"><MessageSquareText className="h-5 w-5 text-brand-green" /></div><div><h2 className="font-semibold text-[var(--text-primary)]">Project messages</h2><p className="mt-1 text-sm text-[var(--text-secondary)]">Direct communication between the project team and client.</p></div></div>
      <Button type="button" variant="secondary" size="sm" onClick={() => void loadMessages()} disabled={isLoading || isSending}><RefreshCw className={`mr-2 h-4 w-4 ${isLoading ? 'animate-spin' : ''}`} />Refresh</Button>
    </div>
    <div className="p-5 sm:p-6">
      {error && <div role="alert" className="mb-5 flex items-start gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700"><AlertCircle className="mt-0.5 h-5 w-5 shrink-0" /><p className="text-sm">{error}</p></div>}
      {isLoading ? <div className="flex min-h-56 flex-col items-center justify-center rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-subtle)]"><LoaderCircle className="h-7 w-7 animate-spin text-brand-green" /><p className="mt-3 text-sm text-[var(--text-secondary)]">Loading project messages...</p></div> : messages.length === 0 ? <div className="flex min-h-56 flex-col items-center justify-center rounded-xl border border-dashed border-[var(--border-default)] bg-[var(--surface-subtle)] px-6 text-center"><MessageSquareText className="h-9 w-9 text-gray-300" /><h3 className="mt-4 font-semibold text-[var(--text-primary)]">No messages yet</h3><p className="mt-2 text-sm text-[var(--text-secondary)]">Start the project conversation with the client.</p></div> : <div className="max-h-[460px] space-y-4 overflow-y-auto rounded-xl bg-[var(--surface-subtle)] p-3 sm:p-4">{messages.map((message) => <article key={message.id} className={`max-w-[88%] rounded-2xl border px-4 py-3 shadow-sm ${message.isCurrentUser ? 'ml-auto border-brand-green/20 bg-brand-green text-white' : 'mr-auto border-[var(--border-subtle)] bg-white text-[var(--text-primary)]'}`}><div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between sm:gap-4"><div><p className="text-sm font-semibold">{message.senderName}</p><p className={`text-xs capitalize ${message.isCurrentUser ? 'text-white/70' : 'text-[var(--text-muted)]'}`}>{message.senderType}</p></div><time dateTime={message.createdAt} className={`text-xs ${message.isCurrentUser ? 'text-white/70' : 'text-[var(--text-muted)]'}`}>{formatMessageDate(message.createdAt)}</time></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6">{message.message}</p></article>)}</div>}
      <form className="mt-6 rounded-xl border border-[var(--border-subtle)] bg-white p-4" onSubmit={sendMessage}><label htmlFor="staff-project-message" className="text-sm font-semibold text-[var(--text-primary)]">New message</label><textarea id="staff-project-message" value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Write a message to the client..." rows={4} maxLength={5000} disabled={isSending} className="mt-2 w-full resize-y rounded-xl border border-[var(--border-default)] bg-white px-4 py-3 text-sm text-[var(--text-primary)] outline-none transition focus:border-brand-green focus:ring-2 focus:ring-brand-green/15 disabled:cursor-not-allowed disabled:opacity-60" /><div className="mt-3 flex items-center justify-between gap-3"><span className="text-xs text-[var(--text-muted)]">{draft.length.toLocaleString()} / 5,000</span><Button type="submit" disabled={!draft.trim() || isSending}>{isSending ? <LoaderCircle className="mr-2 h-4 w-4 animate-spin" /> : <Send className="mr-2 h-4 w-4" />}{isSending ? 'Sending...' : 'Send Message'}</Button></div></form>
    </div>
  </Card>;
}
