-- Migration: 003_support_requests.sql
-- Description: Creates the support_requests table for managing client service requests
-- Created: 2024
-- Dependencies: 001_initial_setup (generate_request_reference function), 002_users_tables (clients table)

-- ============================================================
-- SUPPORT REQUESTS TABLE
-- ============================================================
-- Stores client service requests that may or may not become projects.
-- A support request is NOT a project until explicitly approved and converted.
-- Request reference format: JMT-YYYY-XXXXXX (generated by database function)

-- Create enum type for request status if not exists
DO $$ BEGIN
    CREATE TYPE request_status AS ENUM (
        'New Request',
        'Under Review',
        'Waiting for Documents',
        'Ready for Assessment',
        'Assessment Complete',
        'Recommendation Sent',
        'Waiting for Client Decision',
        'Approved',
        'Declined',
        'Cancelled'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create enum type for priority levels
DO $$ BEGIN
    CREATE TYPE priority_level AS ENUM (
        'Low',
        'Normal',
        'High',
        'Urgent'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create enum type for academic levels
DO $$ BEGIN
    CREATE TYPE academic_level AS ENUM (
        'Undergraduate',
        'Masters',
        'Doctoral'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create enum type for service packages
DO $$ BEGIN
    CREATE TYPE service_package AS ENUM (
        'A - Proposal Development',
        'B - Foundation Thesis',
        'C - Complete Thesis Development',
        'D - Thesis Rescue',
        'E - Formatting & Compliance',
        'F - Defense Presentation'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create the support_requests table
CREATE TABLE IF NOT EXISTS support_requests (
    -- Primary key
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- Reference number (unique, non-editable)
    request_reference TEXT UNIQUE NOT NULL DEFAULT generate_request_reference(),
    
    -- Client relationship
    client_id UUID NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,
    
    -- Service information
    requested_service service_package,
    current_stage TEXT, -- e.g., 'Proposal', 'Literature Review', 'Data Collection', etc.
    
    -- Project details
    working_title TEXT,
    academic_level academic_level,
    submission_deadline DATE,
    
    -- Request details
    support_description TEXT,
    
    -- Status tracking
    status request_status NOT NULL DEFAULT 'New Request',
    priority priority_level NOT NULL DEFAULT 'Normal',
    
    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    -- Additional metadata
    source TEXT DEFAULT 'website', -- website, whatsapp, email, phone
    notes TEXT -- Internal notes
    
);

-- Create index on client_id for faster lookups
CREATE INDEX IF NOT EXISTS idx_support_requests_client_id 
    ON support_requests(client_id);

-- Create index on status for filtering
CREATE INDEX IF NOT EXISTS idx_support_requests_status 
    ON support_requests(status);

-- Create index on request_reference for quick lookups
CREATE INDEX IF NOT EXISTS idx_support_requests_reference 
    ON support_requests(request_reference);

-- Create index on created_at for sorting
CREATE INDEX IF NOT EXISTS idx_support_requests_created_at 
    ON support_requests(created_at DESC);

-- Create composite index for common query patterns
CREATE INDEX IF NOT EXISTS idx_support_requests_client_status 
    ON support_requests(client_id, status);

-- ============================================================
-- UPDATED_AT TRIGGER
-- ============================================================
-- Automatically update the updated_at timestamp when a record is modified

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for support_requests
DROP TRIGGER IF EXISTS trigger_support_requests_updated_at ON support_requests;
CREATE TRIGGER trigger_support_requests_updated_at
    BEFORE UPDATE ON support_requests
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================
-- COMMENTS
-- ============================================================
COMMENT ON TABLE support_requests IS 'Client service requests that may become projects after approval';
COMMENT ON COLUMN support_requests.request_reference IS 'Unique reference number in format JMT-YYYY-XXXXXX';
COMMENT ON COLUMN support_requests.client_id IS 'Reference to the client who submitted the request';
COMMENT ON COLUMN support_requests.requested_service IS 'The service package the client is interested in';
COMMENT ON COLUMN support_requests.current_stage IS 'Current academic/research stage of the project';
COMMENT ON COLUMN support_requests.working_title IS 'Working title for the thesis/project';
COMMENT ON COLUMN support_requests.academic_level IS 'Academic level: Undergraduate, Masters, or Doctoral';
COMMENT ON COLUMN support_requests.submission_deadline IS 'Client target submission date';
COMMENT ON COLUMN support_requests.support_description IS 'Detailed description of support needed';
COMMENT ON COLUMN support_requests.status IS 'Current status of the request';
COMMENT ON COLUMN support_requests.priority IS 'Priority level for processing';
COMMENT ON COLUMN support_requests.source IS 'Origin of the request: website, whatsapp, email, phone';
COMMENT ON COLUMN support_requests.notes IS 'Internal notes for staff';

-- ============================================================
-- VERIFY TABLE CREATION
-- ============================================================
DO $$ 
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables 
        WHERE table_schema = 'public' 
        AND table_name = 'support_requests'
    ) THEN
        RAISE NOTICE 'Table support_requests created successfully';
    ELSE
        RAISE EXCEPTION 'Table support_requests was not created';
    END IF;
END $$;
