-- Migration: 004_projects.sql
-- Description: Creates the projects table for approved service requests
-- Created: 2024
-- Dependencies: 003_support_requests (support_requests table)

-- ============================================================
-- PROJECTS TABLE
-- ============================================================
-- Projects are created ONLY after a support request has been approved.
-- Each support request can have at most ONE project (1:1 relationship).
-- Project reference format: PRJ-YYYY-XXXXXX (generated by database function)

-- Create enum type for project status
DO $$ BEGIN
    CREATE TYPE project_status AS ENUM (
        'Project Activated',
        'Development',
        'Quality Review',
        'Ready for Delivery',
        'Delivered',
        'Completed',
        'Archived'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create enum type for project type (mirrors service packages but simplified)
DO $$ BEGIN
    CREATE TYPE project_type AS ENUM (
        'Proposal Development',
        'Foundation Thesis',
        'Complete Thesis Development',
        'Thesis Rescue',
        'Formatting & Compliance',
        'Defense Presentation'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create the projects table
CREATE TABLE IF NOT EXISTS projects (
    -- Primary key
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- Reference number (unique, non-editable)
    project_reference TEXT UNIQUE NOT NULL DEFAULT generate_project_reference(),
    
    -- Link to the originating support request (1:1 relationship)
    -- This ensures each request can have only one project
    support_request_id UUID UNIQUE NOT NULL REFERENCES support_requests(id) ON DELETE RESTRICT,
    
    -- Client relationship (denormalized for faster queries)
    client_id UUID NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,
    
    -- Project details
    project_title TEXT NOT NULL,
    approved_service project_type NOT NULL,
    
    -- Project timeline
    start_date DATE NOT NULL DEFAULT CURRENT_DATE,
    expected_delivery_date DATE,
    
    -- Progress tracking
    status project_status NOT NULL DEFAULT 'Project Activated',
    completion_percentage INTEGER DEFAULT 0 CHECK (completion_percentage >= 0 AND completion_percentage <= 100),
    
    -- Completion tracking
    completed_at TIMESTAMPTZ,
    
    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    -- Additional metadata
    notes TEXT, -- Internal notes
    archived_at TIMESTAMPTZ -- When project was archived
    
);

-- ============================================================
-- INDEXES
-- ============================================================

-- Index on client_id for faster lookups
CREATE INDEX IF NOT EXISTS idx_projects_client_id 
    ON projects(client_id);

-- Index on support_request_id (should be unique anyway but helps with lookups)
CREATE INDEX IF NOT EXISTS idx_projects_support_request_id 
    ON projects(support_request_id);

-- Index on project_reference for quick lookups
CREATE INDEX IF NOT EXISTS idx_projects_reference 
    ON projects(project_reference);

-- Index on status for filtering
CREATE INDEX IF NOT EXISTS idx_projects_status 
    ON projects(status);

-- Index on start_date for timeline queries
CREATE INDEX IF NOT EXISTS idx_projects_start_date 
    ON projects(start_date);

-- Index on expected_delivery_date for deadline tracking
CREATE INDEX IF NOT EXISTS idx_projects_delivery_date 
    ON projects(expected_delivery_date);

-- Composite index for dashboard queries
CREATE INDEX IF NOT EXISTS idx_projects_client_status 
    ON projects(client_id, status);

-- Index for active projects (performance optimization)
CREATE INDEX IF NOT EXISTS idx_projects_active 
    ON projects(status) WHERE status NOT IN ('Completed', 'Archived');

-- ============================================================
-- UPDATED_AT TRIGGER
-- ============================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for projects
DROP TRIGGER IF EXISTS trigger_projects_updated_at ON projects;
CREATE TRIGGER trigger_projects_updated_at
    BEFORE UPDATE ON projects
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================
-- AUTO-COMPLETION TRIGGER
-- ============================================================
-- Automatically set completed_at when status changes to 'Completed'

CREATE OR REPLACE FUNCTION set_completed_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.status = 'Completed' AND OLD.status != 'Completed' THEN
        NEW.completed_at = NOW();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_projects_completed_at ON projects;
CREATE TRIGGER trigger_projects_completed_at
    BEFORE UPDATE ON projects
    FOR EACH ROW
    EXECUTE FUNCTION set_completed_timestamp();

-- ============================================================
-- CONSTRAINTS
-- ============================================================

-- Ensure delivery date is after start date
ALTER TABLE projects DROP CONSTRAINT IF EXISTS check_delivery_date;
ALTER TABLE projects ADD CONSTRAINT check_delivery_date 
    CHECK (expected_delivery_date IS NULL OR expected_delivery_date >= start_date);

-- Ensure completed_at is set when status is Completed
ALTER TABLE projects DROP CONSTRAINT IF EXISTS check_completed_at;
ALTER TABLE projects ADD CONSTRAINT check_completed_at 
    CHECK (status != 'Completed' OR completed_at IS NOT NULL);

-- ============================================================
-- COMMENTS
-- ============================================================
COMMENT ON TABLE projects IS 'Approved service requests converted to active projects';
COMMENT ON COLUMN projects.project_reference IS 'Unique reference number in format PRJ-YYYY-XXXXXX';
COMMENT ON COLUMN projects.support_request_id IS 'Link to originating support request (1:1)';
COMMENT ON COLUMN projects.client_id IS 'Reference to the client (denormalized for performance)';
COMMENT ON COLUMN projects.project_title IS 'Official project title';
COMMENT ON COLUMN projects.approved_service IS 'The approved service package';
COMMENT ON COLUMN projects.start_date IS 'Project start date';
COMMENT ON COLUMN projects.expected_delivery_date IS 'Expected completion date';
COMMENT ON COLUMN projects.status IS 'Current project status';
COMMENT ON COLUMN projects.completion_percentage IS 'Project completion percentage (0-100)';
COMMENT ON COLUMN projects.completed_at IS 'Timestamp when project was marked completed';
COMMENT ON COLUMN projects.archived_at IS 'Timestamp when project was archived';
COMMENT ON COLUMN projects.notes IS 'Internal notes for staff';

-- ============================================================
-- VERIFY TABLE CREATION
-- ============================================================
DO $$ 
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables 
        WHERE table_schema = 'public' 
        AND table_name = 'projects'
    ) THEN
        RAISE NOTICE 'Table projects created successfully';
    ELSE
        RAISE EXCEPTION 'Table projects was not created';
    END IF;
END $$;
